<project name="top_app" version="1.2">
    <ProjectDirectory>
        C:\repo1\gpb\stn\fpga_app\designer\top_app\top_app_fp_test\top_app
    </ProjectDirectory>
    <View>
        ChainView
    </View>
    <LiberoTargetDevice>
        
    </LiberoTargetDevice>
    <LogFile>
        C:\repo1\gpb\stn\fpga_app\designer\top_app\top_app_fp_test\top_app\top_app.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <ProgrammingInterface>
        JTAGMode
    </ProgrammingInterface>
    <programmer status="enable" type="FlashPro4" revision="UndefRev" connection="usb1.1">
        <name>
            04404
        </name>
        <id>
            04404
        </id>
    </programmer>
    <Servers>
    </Servers>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro5>
            <FlashPro6>
                <TCK>
                    4000000
                </TCK>
                <SCK>
                    20000000
                </SCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro6>
        </Hardware>
        <Device type="ACTEL">
            <Name>
                MPF100T
            </Name>
            <Custom>
                MPF100T
            </Custom>
            <SpiFlashFile>
                
            </SpiFlashFile>
            <SpiFlashSelectedAction>
                
            </SpiFlashSelectedAction>
            <Algo type="STAPL">
                <filename>
                    C:\repo1\gpb\stn\fpga_app\designer\top_app\top_app_fp_test\top_app\top_app.stp
                </filename>
                <local>
                    projectData\top_app.stp
                </local>
                <SelectedAction>
                    DEVICE_INFO
                </SelectedAction>
                <Action name="PROGRAM" deselectedProcedures="DO_VERIFY">
                </Action>
            </Algo>
        </Device>
        <Algo type="unknown">
            <irlength>
                0
            </irlength>
            <MaxTCK>
                0
            </MaxTCK>
        </Algo>
    </configuration>
</project>
